baseURL: "https://ishaanadarsh.github.io"
languageCode: en-us
title: Blind Guys Paradise
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: about
      name: About
      url: /about
      weight: 30
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  author: Ishaan Adarsh
  description: Portfolio and Blog
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  homeInfoParams:
    Title: Welcome
    Content: >-
      
      - My name is Ishaan Adarsh, I write about my tech journey and some other dumb stuff.
      
      - 
      
      - i'm an aspiring corporate robot who likes to code occasionally. In my spare time, I enjoy playing video games, watching old irrelevant movies, and staring into the vast nothingness.

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "github"
      url: "https://github.com/IshaanAdarsh"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/ishaan-adarsh-161a56222/"
    - name: "email"
      url: "mailto:ishaanad9@gmail.com"
    - name: "instagram"
      url: "https://www.instagram.com/ishaan_adarsh_/"
    

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
